services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@1234
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root@1234
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
